# Expected file locations (replace with your actual files)
paths:
  matches: "data/raw/matches.csv"        # one row per match per team (home & away as separate rows)
  events: "data/raw/events.csv"          # atomic events (shots, passes, duels...)
  squads: "data/raw/squads.csv"          # squad list per match (XI + bench)
  injuries: "data/raw/injuries.csv"      # optional
  players: "data/raw/players.csv"        # player master (id, name, dob, position)

# Column mapping: adapt these to your dataset
schema:
  matches:
    required: [match_id, match_date, competition, season, team_id, opponent_id, venue, formation, goals_for, goals_against]
    dtypes:
      match_id: int64
      match_date: datetime64[ns]
      competition: string
      season: string
      team_id: string
      opponent_id: string
      venue: category
      formation: string
      goals_for: int64
      goals_against: int64
  squads:
    required: [match_id, team_id, player_id, in_xi, on_bench, minutes, position]
  events:
    required: [match_id, team_id, player_id, event_type, minute, outcome, xg]
  players:
    required: [player_id, name, primary_position, footedness, birth_date]

# Feature windows for Week-1 sanity
feature_windows: [3, 5, 10]

# Report
profile_report_path: "outputs/reports/data_profile.html"
