name: football-squad-selection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.2.1
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - notebook=7.0.2
  - ipykernel=6.25.0
  - pyyaml=6.0.1
  - requests=2.31.0
  - tqdm=4.65.0
  - joblib=1.3.1
  - psutil=5.9.5
  - statsmodels=0.14.0
  - pip:
    - lightgbm==4.0.0
    - xgboost==1.7.6
    - optuna==3.2.0
    - mlflow==2.5.0
    - pulp==2.7.0
    - ortools==9.7.2996
    - implicit==0.7.2
    - plotly==5.15.0
    - statsbombpy==1.11.0
    - soccerdata==1.4.0
    - beautifulsoup4==4.12.2
    - python-dotenv==1.0.0
    - click==8.1.6
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - black==23.7.0
    - flake8==6.0.0
    - mypy==1.5.1
    - pingouin==0.5.3
    - tslearn==0.6.2
    - shap==0.42.1
    - lime==0.2.0.1
    - pickle5==0.0.11
    - dill==0.3.7
    - loguru==0.7.0
    - memory-profiler==0.61.0
    - dask==2023.7.1
